import type { Language } from "@/lib/types";

export const copy = {
  en: {
    annualLeave: "Leave and overtime management",
    employee: "Employee",
    calendar: "Calendar",
    supervisor: "Supervisor",
    manager: "Manager",
    welcome: "Welcome",
    employeeIntro: "Search by first name, surname, nickname or employee ID.",
    searchEmployee: "Search employee",
    searchPlaceholder: "Type a name, nickname or employee ID",
    recentEmployees: "Employees",
    selectEmployee: "Select an employee to continue",
    availableBalance: "Available balance",
    earnedThisYear: "Earned this year",
    usedThisYear: "Approved leave used",
    department: "Department",
    requestLeave: "Request annual leave",
    annualLeaveTab: "Annual leave",
    overtimeTab: "Overtime",
    requestOvertime: "Declare overtime",
    startDate: "Start date",
    endDate: "End date",
    overtimeDate: "Overtime date",
    startTime: "Start time",
    endTime: "End time",
    breakMinutes: "Break (minutes)",
    reason: "Reason",
    comment: "Comment",
    commentPlaceholder: "Optional comment",
    reasonPlaceholder: "Why was overtime required?",
    requestedDays: "Requested days",
    balanceAfter: "Balance after request",
    totalHours: "Total overtime",
    leaveRule: "Saturday counts as leave. Sunday does not count.",
    overtimeRule: "Overnight overtime is supported. Break time is deducted automatically.",
    submitRequest: "Submit request",
    submitOvertime: "Submit overtime",
    myRequests: "My leave requests",
    myOvertime: "My overtime requests",
    noRequests: "No request for this employee.",
    noOvertime: "No overtime request for this employee.",
    submitted: "Request submitted for supervisor approval.",
    overtimeSubmitted: "Overtime submitted for supervisor approval.",
    invalidDates: "Select valid start and end dates.",
    invalidOvertime: "Enter a valid date and positive overtime duration.",
    insufficientBalance: "Not enough leave balance.",
    leaveCalendar: "Leave calendar",
    allDepartments: "All departments",
    weekOf: "Week containing",
    working: "Working",
    approvedLeave: "Approved",
    pendingSupervisor: "Pending supervisor",
    pendingManager: "Pending manager",
    rejected: "Rejected",
    cancelled: "Cancelled",
    pendingRequests: "Pending requests",
    teamSize: "Team size",
    onLeaveToday: "On leave today",
    totalEmployees: "Total employees",
    approvedThisMonth: "Approved this month",
    firstApproval: "First approval",
    finalApproval: "Final approval",
    period: "Period",
    days: "days",
    hours: "hours",
    status: "Status",
    action: "Action",
    noPending: "No pending request.",
    changeEmployee: "Change employee",
    liveDatabase: "Live Supabase database",
    loading: "Loading plant data…",
    retry: "Retry",
    databaseError: "The application could not load Supabase data.",
    secureApproval: "Approval buttons will be activated after supervisor and manager login is configured.",
    refresh: "Refresh data",
    unassigned: "Unassigned",
  },
  oshi: {
    annualLeave: "Eendjokelwa doleave no overtime",
    employee: "Omunambelewa",
    calendar: "Kalendere",
    supervisor: "Supervisor",
    manager: "Manager",
    welcome: "Wa uhala po",
    employeeIntro: "Konga edhina, surname, nickname ile employee ID.",
    searchEmployee: "Konga omunambelewa",
    searchPlaceholder: "Nyola edhina, nickname ile employee ID",
    recentEmployees: "Aananambelewa",
    selectEmployee: "Hogolola omunambelewa opo u twikile",
    availableBalance: "Eendjoka da li po",
    earnedThisYear: "Leave ya monika momudo",
    usedThisYear: "Leave ya pitikwa ya longithwa",
    department: "Department",
    requestLeave: "Lomba annual leave",
    annualLeaveTab: "Annual leave",
    overtimeTab: "Overtime",
    requestOvertime: "Nyola overtime",
    startDate: "Efiku lotango",
    endDate: "Efiku laxuuninwa",
    overtimeDate: "Efiku lo overtime",
    startTime: "Ethimbo lotango",
    endTime: "Ethimbo laxuuninwa",
    breakMinutes: "Break (ominute)",
    reason: "Omolwa shike",
    comment: "Oshitya",
    commentPlaceholder: "Oshitya tashi dulu okushiywa",
    reasonPlaceholder: "Omolwa shike overtime ya pumbiwa?",
    requestedDays: "Eendjoka dalombwa",
    balanceAfter: "Balance konima yelombwelo",
    totalHours: "Omahora go overtime",
    leaveRule: "Saturday ota balwa. Sunday ita balwa.",
    overtimeRule: "Overtime youfiku nofikola ota dulu okunyolwa. Break ota minuswa.",
    submitRequest: "Tumitha elombwelo",
    submitOvertime: "Tumitha overtime",
    myRequests: "Omalombwelo gange goleave",
    myOvertime: "Omalombwelo gange go overtime",
    noRequests: "Kape na elombwelo lyomunambelewa nguka.",
    noOvertime: "Kape na elombwelo lo overtime.",
    submitted: "Elombwelo lya tumithwa kosupervisor.",
    overtimeSubmitted: "Overtime ya tumithwa kosupervisor.",
    invalidDates: "Hogolola omafiku mahawa.",
    invalidOvertime: "Nyola efiku noma hora mahawa.",
    insufficientBalance: "Eendjoka dileave inadi gwana.",
    leaveCalendar: "Kalendere yoleave",
    allDepartments: "Departments adishe",
    weekOf: "Oshivike shi na efiku",
    working: "Ota longo",
    approvedLeave: "Ya pitikwa",
    pendingSupervisor: "Ota teelele supervisor",
    pendingManager: "Ota teelele manager",
    rejected: "Inashi pitikwa",
    cancelled: "Ya cancelwa",
    pendingRequests: "Omalombwelo taga teelele",
    teamSize: "Aantu mekwata",
    onLeaveToday: "Mo leave nena",
    totalEmployees: "Aananambelewa aveshe",
    approvedThisMonth: "Ya pitikwa momwedhi nguka",
    firstApproval: "Epitiko lyotango",
    finalApproval: "Epitiko laxuuninwa",
    period: "Omafiku",
    days: "eendjoka",
    hours: "omahora",
    status: "Oshiningwanima",
    action: "Longa",
    noPending: "Kape na elombwelo tali teelele.",
    changeEmployee: "Hogolola mukwao",
    liveDatabase: "Supabase database",
    loading: "Odata otayi longwa…",
    retry: "Tameka vali",
    databaseError: "App ina dulu okumona odata mo Supabase.",
    secureApproval: "Omapitiko otaga vulwa konima yokulongitha login yosupervisor nomanager.",
    refresh: "Nyanyudha odata",
    unassigned: "Inayi tulwa mo department",
  },
} satisfies Record<Language, Record<string, string>>;
