import type { Employee, LeaveRequest } from "@/lib/types";

export const employees: Employee[] = [
  {
    id: "EMP0142",
    firstName: "John",
    surname: "Nghipandulwa",
    nickname: "Johnny",
    department: "Production",
    supervisor: "Paulus Uugwanga",
    manager: "David Shikomba",
    balance: 12,
    earned: 16,
    used: 4,
  },
  {
    id: "EMP0087",
    firstName: "Maria",
    surname: "Amutenya",
    nickname: "Meme",
    department: "Laboratory",
    supervisor: "Helena Nashandi",
    manager: "David Shikomba",
    balance: 8,
    earned: 16,
    used: 8,
  },
  {
    id: "EMP0211",
    firstName: "Petrus",
    surname: "Shikongo",
    nickname: "Peya",
    department: "Maintenance",
    supervisor: "Petrus Simon",
    manager: "David Shikomba",
    balance: 16,
    earned: 16,
    used: 0,
  },
  {
    id: "EMP0164",
    firstName: "Elina",
    surname: "Uutoni",
    nickname: "Lina",
    department: "Production",
    supervisor: "Paulus Uugwanga",
    manager: "David Shikomba",
    balance: 10,
    earned: 16,
    used: 6,
  },
  {
    id: "EMP0319",
    firstName: "George",
    surname: "Nekale",
    nickname: "G",
    department: "Logistics",
    supervisor: "Paulus Uugwanga",
    manager: "David Shikomba",
    balance: 6,
    earned: 16,
    used: 10,
  },
  {
    id: "EMP0195",
    firstName: "Anna",
    surname: "Shikongo",
    nickname: "Nana",
    department: "Warehouse",
    supervisor: "Immanuel Kambonde",
    manager: "David Shikomba",
    balance: 14,
    earned: 16,
    used: 2,
  },
  {
    id: "EMP0233",
    firstName: "Johannes",
    surname: "Sheehama",
    nickname: "Jossy",
    department: "Maintenance",
    supervisor: "Petrus Simon",
    manager: "David Shikomba",
    balance: 18,
    earned: 20,
    used: 2,
  },
  {
    id: "EMP0290",
    firstName: "Helena",
    surname: "Nashandi",
    nickname: "Lena",
    department: "Laboratory",
    supervisor: "Helena Nashandi",
    manager: "David Shikomba",
    balance: 20,
    earned: 20,
    used: 0,
  },
];

export const initialRequests: LeaveRequest[] = [
  {
    id: "REQ-1001",
    employeeId: "EMP0142",
    startDate: "2026-07-20",
    endDate: "2026-07-23",
    days: 4,
    comment: "Family matters",
    status: "approved",
    createdAt: "2026-07-02T08:15:00.000Z",
  },
  {
    id: "REQ-1002",
    employeeId: "EMP0164",
    startDate: "2026-07-21",
    endDate: "2026-07-24",
    days: 4,
    comment: "Travel",
    status: "pending_supervisor",
    createdAt: "2026-07-08T09:30:00.000Z",
  },
  {
    id: "REQ-1003",
    employeeId: "EMP0319",
    startDate: "2026-07-22",
    endDate: "2026-07-25",
    days: 4,
    comment: "Personal leave",
    status: "pending_manager",
    createdAt: "2026-07-09T11:00:00.000Z",
  },
  {
    id: "REQ-1004",
    employeeId: "EMP0087",
    startDate: "2026-07-27",
    endDate: "2026-07-31",
    days: 5,
    comment: "Family visit",
    status: "approved",
    createdAt: "2026-07-01T06:45:00.000Z",
  },
];
